import Header from '@/app/Header';
import '../styles/globals.css';
import { Social } from '@/typing';
import { fetchSocials } from '@/utils/fetchSocials';
import Providers from './Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const socialLinks= await fetchSocials();
  return (
    <html lang="en">
      <body className='overflow-x-hidden bg-violet-50 text-zinc-800 dark:bg-zinc-900 dark:text-white overflow-y-scroll scrollbar-hide'>
          <Providers>
            <Header socialLinks={socialLinks} />
          <div>{children}</div>
          </Providers>
      </body>
    </html>
  )
}
